name: annotate sheets
'on':
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
    - name: Setup Python environment for sltx
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup and run sltx-install + xlsx2csv
      run: |
        pip install sltx
        echo "tx-full" | sltx docker
        sudo apt install xlsx2csv poppler-utils imagemagick-6-common ghostscript-x
        sudo cp custom-policy.xml /etc/ImageMagick-6/policy.xml
    - name: Compile the Documents
      run: |
        make annotate ARGS='compile --root --profile "tx-full"'
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f "Output-Deck.json"
        git commit -m "The annotation"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
